blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/chad-loder/nx-project-types/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://github.com/chad-loder/nx-project-types/tree/main/docs
    about: Check the documentation before reporting issues
